# Copyright Bosch Software Innovations GmbH, 2019.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

# This uses the docker config feature, which only works with stack with API 1.30+
# see: https://docs.docker.com/engine/reference/commandline/config/

version: '3.5'

configs:
  sw360.properties:
    file: ../configuration/sw360/sw360.properties
  portal-ext.properties:
    file: ../configuration/sw360/portal-ext.properties
  ldapimporter.properties:
    file: ../configuration/sw360/ldapimporter.properties

services:
  sw360:
    configs:
      - sw360.properties
      - portal-ext.properties
      - ldapimporter.properties
