# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

# This file adds a cve-search server to the sw360 environment.
# Use it together with the main docker-compose.yml as described
# in README.md

version: '3.5'
services:
  sw360redis:
    ports:
      - 6379:6379

  sw360mongodb:
    ports:
      - 27017:27017
      - 28017:28017
