# Copyright Bosch Software Innovations GmbH, 2019.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

# This emulates the docker config feature for docker-compose, with read-only bind mounts

version: '3.5'

x-sw360-sw360-properties-mount:
  &sw360-sw360-properties-mount
  type: bind
  source: ../configuration/sw360/sw360.properties
  target: /sw360.properties
  read_only: true
x-sw360-portal-ext-properties-mount:
  &sw360-portal-ext-properties-mount
  type: bind
  source: ../configuration/sw360/portal-ext.properties
  target: /portal-ext.properties
  read_only: true
x-sw360-ldapimporter-properties-mount:
  &sw360-ldapimporter-properties-mount
  type: bind
  source: ../configuration/sw360/ldapimporter.properties
  target: /ldapimporter.properties
  read_only: true

services:
  sw360:
    volumes:
      - *sw360-sw360-properties-mount
      - *sw360-portal-ext-properties-mount
      - *sw360-ldapimporter-properties-mount
