# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

# This file adds a cve-search server to the sw360 environment.
# Use it together with the main docker-compose.yml as described
# in README.md

version: '3.7'
services:

  sw360:
    depends_on:
      - sw360cvesearch
    environment:
      - CVE_SEARCH_HOST=http://sw360cvesearch:5000
      
  sw360cvesearch:
    image: sw360cvesearch
    container_name: ${COMPOSE_PROJECT_NAME}_sw360cvesearch
    restart: unless-stopped
    environment:
      - REDIS_HOST=sw360redis
      - MONGODB_HOST=sw360mongodb
    command: server
    networks:
      - sw360front
      - cevsearchDBs
    depends_on:
      - sw360mongodb
      - sw360redis
    ports:
      - 5000:5000

  sw360cvesearchUpdater:
    image: sw360cvesearch
    container_name: ${COMPOSE_PROJECT_NAME}_sw360cvesearchUpdater
    restart: unless-stopped
    environment:
      - REDIS_HOST=sw360redis
      - MONGODB_HOST=sw360mongodb
    command: updater
    env_file: ../configuration/proxy.env
    networks:
      - sw360front
      - cevsearchDBs
    depends_on:
      - sw360mongodb
      - sw360redis

  sw360redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_sw360redis
    restart: unless-stopped
    networks:
      - cevsearchDBs

  sw360mongodb:
    image: mongo
    container_name: ${COMPOSE_PROJECT_NAME}_sw360mongodb
    restart: unless-stopped
    networks:
      - cevsearchDBs

networks:
  cevsearchDBs:
    ipam:
      driver: default
      config:
        - subnet: 172.29.7.0/24
          gateway: 172.29.7.254
